spring.application.name=practicacrud

spring.datasource.url=jdbc:postgresql://localhost:5432/crudspingboot
spring.datasource.username=postgres
spring.datasource.password=oasis2100
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080